services:
  loki:
    image: grafana/loki:2.9.0
    container_name: akira_loki
    ports:
      - "3100:3100"
    command: -config.expand-env=true -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - ./loki/data:/loki

  prometheus:
    image: prom/prometheus
    container_name: akira_prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: akira_grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
      - prometheus
#      - web-service

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml
      - ./tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo
      - "4317:4317" # OTLP
      - "4318:4318" # HTTP
    hostname: tempo

volumes:
  prom_data:
